'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:2.0.50727.3615
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Xydc.Platform.web

    Partial Public Class bannerTitle

        '''<summary>
        '''htxtAutoRefreshEnabled 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtAutoRefreshEnabled As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtAutoRefreshTime 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtAutoRefreshTime As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtInfoCount 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtInfoCount As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''lblRealtimeMessage 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lblRealtimeMessage As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblUserXM 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lblUserXM As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblUserBMMC 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lblUserBMMC As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblUserEnterTime 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lblUserEnterTime As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''htxtUserEnterTime 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtUserEnterTime As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtFullScreen 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtFullScreen As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtLockApp 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtLockApp As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    End Class
End Namespace
