'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行库版本:2.0.50727.1433
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Xydc.Platform.web

    Partial Public Class main

        '''<summary>
        '''frmMAIN 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents frmMAIN As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''panelMain 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents panelMain As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lnkBlank 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lnkBlank As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkMenu 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lnkMenu As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''htxtSelectMenuID 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtSelectMenuID As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''mnuMain 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuMain As Global.ComponentArt.Web.UI.Menu

        '''<summary>
        '''mnuXTZY 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuXTZY As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuXTZY_1001 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuXTZY_1001 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuXTZY_Bar1 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuXTZY_Bar1 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuXTZY_2001 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuXTZY_2001 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuXTZY_2002 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuXTZY_2002 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuXTZY_Bar2 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuXTZY_Bar2 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuXTZY_3001 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuXTZY_3001 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuTop_Bar05 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuTop_Bar05 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuSunshine 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuSunshine As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuSunshine_005 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuSunshine_005 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuSunshine_007 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuSunshine_007 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuSunshine_002 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuSunshine_002 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuSunshine_003 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuSunshine_003 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuSunshine_004 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuSunshine_004 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuSunshine_006 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuSunshine_006 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuTop_Bar09 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuTop_Bar09 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuDayData 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuDayData As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuDayData_01 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuDayData_01 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuDayData_02 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuDayData_02 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuDayData_03 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuDayData_03 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuDayData_04 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuDayData_04 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuTop_Bar11 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuTop_Bar11 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuDayData_001 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuDayData_001 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuDayData_002 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuDayData_002 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuDayData_003 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuDayData_003 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuDayData_004 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuDayData_004 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuDayData_005 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuDayData_005 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuDayData_006 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuDayData_006 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuTop_Bar06 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuTop_Bar06 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuDepthData 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuDepthData As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuDepthData_1001 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuDepthData_1001 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuDepthData_1002 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuDepthData_1002 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuDepthData_1003 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuDepthData_1003 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuTop_Bar04 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuTop_Bar04 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuCustomer 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuCustomer As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuCustomer_001 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuCustomer_001 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuCustomer_002 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuCustomer_002 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuCustomer_003 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuCustomer_003 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuCustomer_medium 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuCustomer_medium As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuCustomer_medium_001 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuCustomer_medium_001 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuTop_Bar07 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuTop_Bar07 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuSJPZ 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuSJPZ As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuSJPZ_1001 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuSJPZ_1001 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuSJPZ_1002 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuSJPZ_1002 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuSJPZ_1003 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuSJPZ_1003 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuSJPZ_1004 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuSJPZ_1004 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuSJPZ_Bra1 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuSJPZ_Bra1 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuSJPZ_1005 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuSJPZ_1005 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuSJPZ_1006 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuSJPZ_1006 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuSJPZ_1007 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuSJPZ_1007 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuTop_Bar08 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuTop_Bar08 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuXTPZ 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuXTPZ As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuXTPZ_1001 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuXTPZ_1001 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuXTPZ_Bar1 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuXTPZ_Bar1 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuXTPZ_2001 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuXTPZ_2001 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuXTPZ_2002 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuXTPZ_2002 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuXTGL 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuXTGL As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuXTGL_1001 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuXTGL_1001 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuXTGL_Bar1 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuXTGL_Bar1 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuXTGL_2001 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuXTGL_2001 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuXTGL_2002 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuXTGL_2002 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuXTGL_2003 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuXTGL_2003 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuXTGL_2004 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuXTGL_2004 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuXTGL_Bar2 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuXTGL_Bar2 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuXTGL_3001 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuXTGL_3001 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuXTGL_3002 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuXTGL_3002 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuXTGL_Bar3 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuXTGL_Bar3 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuXTGL_4001 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuXTGL_4001 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuXTGL_4002 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuXTGL_4002 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuXTGL_4003 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuXTGL_4003 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuXTGL_4004 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuXTGL_4004 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuXTGL_4005 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuXTGL_4005 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuXTGL_Bar4 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuXTGL_Bar4 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuXTGL_5001 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuXTGL_5001 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuXTGL_5002 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuXTGL_5002 As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''strDisplay_dbsy 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents strDisplay_dbsy As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''panelError 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents panelError As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblMessage 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''popMessageObject 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents popMessageObject As Global.Josco.Web.PopMessage
    End Class
End Namespace
