'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:2.0.50727.3615
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Xydc.Platform.web

    Partial Public Class userinfo

        '''<summary>
        '''frmLogin 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents frmLogin As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''panelInformation 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents panelInformation As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''btnReturn 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents btnReturn As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''txtRYDM 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtRYDM As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''txtRYMC 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtRYMC As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''txtRYZM 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtRYZM As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''txtZZMC 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtZZMC As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''txtRYXH 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtRYXH As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''txtJBMC 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtJBMC As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''txtMSMC 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtMSMC As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''txtLXDH 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtLXDH As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''txtSJHM 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtSJHM As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''txtYXDZ 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtYXDZ As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''txtKCKRY 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtKCKRY As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''txtJJXSMC 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtJJXSMC As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''txtKZSRY 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtKZSRY As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''txtQTYZS 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtQTYZS As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''chklstGW 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents chklstGW As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''popMessageObject 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents popMessageObject As Global.Josco.Web.PopMessage
    End Class
End Namespace
