'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:2.0.50727.3615
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Xydc.Platform.web

    Partial Public Class xtpz_dbsz

        '''<summary>
        '''frmXTPZ_DBSZ 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents frmXTPZ_DBSZ As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''panelMain 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents panelMain As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lnkBlank 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lnkBlank As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''txtDBSZSearch_ZWMC 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtDBSZSearch_ZWMC As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtDBSZSearch_DBFW 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtDBSZSearch_DBFW As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtDBSZSearch_BCSM 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtDBSZSearch_BCSM As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnDBSZQuery 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents btnDBSZQuery As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''grdDBSZ 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents grdDBSZ As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''htxtDBSZFixed 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtDBSZFixed As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''lnkCZDBSZDeSelectAll 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lnkCZDBSZDeSelectAll As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkCZDBSZSelectAll 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lnkCZDBSZSelectAll As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkCZDBSZMoveFirst 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lnkCZDBSZMoveFirst As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkCZDBSZMovePrev 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lnkCZDBSZMovePrev As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkCZDBSZMoveNext 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lnkCZDBSZMoveNext As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkCZDBSZMoveLast 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lnkCZDBSZMoveLast As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkCZDBSZGotoPage 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lnkCZDBSZGotoPage As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''txtDBSZPageIndex 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtDBSZPageIndex As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lnkCZDBSZSetPageSize 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lnkCZDBSZSetPageSize As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''txtDBSZPageSize 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtDBSZPageSize As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblDBSZGridLocInfo 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lblDBSZGridLocInfo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''btnDBSZAddNew 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents btnDBSZAddNew As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnDBSZModify 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents btnDBSZModify As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnDBSZDelete 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents btnDBSZDelete As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnDBSZSearch 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents btnDBSZSearch As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnClose 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents btnClose As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''txtZWMC 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtZWMC As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lnkCZSelectZW 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lnkCZSelectZW As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''htxtZWDM 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtZWDM As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''ddlDBFW 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents ddlDBFW As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlBCSM 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents ddlBCSM As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''btnSave 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnCancel 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''panelError 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents panelError As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblMessage 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''htxtSessionIdDBSZQuery 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtSessionIdDBSZQuery As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtCurrentPage 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtCurrentPage As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtCurrentRow 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtCurrentRow As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtEditMode 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtEditMode As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtEditType 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtEditType As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtDBSZQuery 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtDBSZQuery As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtDBSZRows 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtDBSZRows As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtDBSZSort 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtDBSZSort As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtDBSZSortColumnIndex 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtDBSZSortColumnIndex As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtDBSZSortType 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtDBSZSortType As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtDivLeftDBSZ 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtDivLeftDBSZ As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtDivTopDBSZ 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtDivTopDBSZ As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtDivLeftBody 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtDivLeftBody As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtDivTopBody 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtDivTopBody As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''popMessageObject 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents popMessageObject As Global.Josco.Web.PopMessage
    End Class
End Namespace
