'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:2.0.50727.3615
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Xydc.Platform.web

    Partial Public Class ggdm_bmry_ryxx

        '''<summary>
        '''frmGGDM_BMRY_RYXX 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents frmGGDM_BMRY_RYXX As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''panelMain 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents panelMain As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lnkBlank 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lnkBlank As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''txtRYDM 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtRYDM As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtRYMC 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtRYMC As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtRYZM 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtRYZM As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtZZMC 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtZZMC As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnSelectZZDM 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents btnSelectZZDM As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''htxtZZDM 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtZZDM As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''txtRYXH 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtRYXH As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtJBMC 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtJBMC As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnSelectJBDM 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents btnSelectJBDM As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''htxtJBDM 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtJBDM As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''txtMSMC 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtMSMC As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnSelectMSDM 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents btnSelectMSDM As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''htxtMSDM 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtMSDM As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''txtLXDH 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtLXDH As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtSJHM 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtSJHM As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtFTPDZ 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtFTPDZ As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtYXDZ 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtYXDZ As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''chkZDQS 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents chkZDQS As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''txtKZSRY 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtKZSRY As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnSelectKZSRY 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents btnSelectKZSRY As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''txtQTYZS 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtQTYZS As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnSelectQTYZS 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents btnSelectQTYZS As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''htxtQTYZS 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtQTYZS As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''txtKCKXM 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtKCKXM As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnSelectKCKXM 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents btnSelectKCKXM As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''txtJJXSMC 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtJJXSMC As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cblDRZW 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents cblDRZW As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''grdRY 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents grdRY As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''htxtTASKFixed 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtTASKFixed As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''btnOK 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents btnOK As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnCancel 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnClose 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents btnClose As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''panelError 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents panelError As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblMessage 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''htxtBH 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtBH As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtDivLeftMain 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtDivLeftMain As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtDivTopMain 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtDivTopMain As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtDivLeftBody 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtDivLeftBody As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtDivTopBody 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtDivTopBody As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtTASKQuery 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtTASKQuery As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtTASKRows 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtTASKRows As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtTASKSort 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtTASKSort As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtTASKSortColumnIndex 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtTASKSortColumnIndex As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtTASKSortType 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtTASKSortType As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtDivLeftTASK 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtDivLeftTASK As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtDivTopTASK 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtDivTopTASK As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''popMessageObject 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents popMessageObject As Global.Josco.Web.PopMessage
    End Class
End Namespace
